Feature/sckan 167
MetaCell/sckan-composer pull request #159
Opened 2023-10-04 14:28 UTC by Salam-Dalloul

2023-10-04 14:59 UTC, zsinnema approved these changes

2023-10-04 16:47 UTC, zsinnema commented
@Salam-Dalloul still draft?

2023-10-05 19:52 UTC, afonsobspinto commented on backend/composer/api/filtersets.py
> +    def filter_sentence_id(self, queryset, name, value):
Done :+1:

2023-10-09 08:26 UTC, ddelpiano commented
@Salam-Dalloul @afonsobspinto is this still a draft? Thx

2023-10-09 10:27 UTC, afonsobspinto commented
Still a draft. What's missing:
- UI for business logic errors (invalid forward connection)
- UI for No results

2023-10-09 15:01 UTC, zsinnema submitted a review, later dismissed

2023-10-10 11:27 UTC, zsinnema requested changes

2023-10-10 11:27 UTC, zsinnema commented on backend/composer/api/views.py
> +        data.pop('state', None)
@afonsobspinto suggestion: would this work: pop it from the request.data and then call `.super()`

2023-10-10 11:27 UTC, zsinnema commented on backend/composer/services/state_services.py
> +                sentence.pmid is not None
@afonsobspinto is this correct: 2 indents?

2023-10-10 11:27 UTC, zsinnema commented on backend/composer/services/state_services.py
> +                connectivity_statement.origin is not None
@afonsobspinto same here

2023-10-11 08:05 UTC, afonsobspinto requested changes
Also update the export according to @ddelpiano message:
> for the export:
the relationship = forward connection;
the structure = neuron population label of the forward connection;
the identifier = NLP-ID;
the predicate = ilxtr:hasForwardConnectionPhenotype

2023-10-11 14:03 UTC, zsinnema approved these changes

2023-10-11 22:22 UTC, afonsobspinto approved these changes
Tested the export and looks good to me :+1: 

![image](https://github.com/MetaCell/sckan-composer/assets/19196034/b6ab282f-16fc-489e-bb5f-f12c5bd6710f)

2023-10-12 06:38 UTC, merged