#197 Add current options as part of selected options
MetaCell/sckan-composer pull request #175
Opened 2023-11-15 14:27 UTC by Salam-Dalloul

2023-11-15 14:46 UTC, zsinnema approved these changes

2023-11-16 10:04 UTC, afonsobspinto commented on frontend/src/components/Forms/StatementForm.tsx
> +            return getAnatomicalEntitiesForForm(
This doesn't seem right. It should be using `searchFromEntitiesVia`

2023-11-16 10:06 UTC, afonsobspinto requested changes
The search on the from is different from the search on the anatomical entities but it's being treated equally in the current PR. Please keep the logic from 'searchFromEntitiesVia' and 'searchFromEntitiesDestination'

2023-11-16 13:39 UTC, afonsobspinto commented on frontend/src/services/CustomDropdownService.ts
> +  const anatomicalEntities = getEntitiesBeforeOrder(statement, viaOrder);
Although practically speaking it's unlikely that we will need it, we should still use the current selected options in the searchFromEntitiesX functions to populate the anatomicalEntities options (without creating duplicates)

2023-11-16 13:39 UTC, afonsobspinto requested changes
Looks better but see my comment above :arrow_up:

2023-11-16 14:54 UTC, afonsobspinto approved these changes

2023-11-16 14:57 UTC, zsinnema commented
@Salam-Dalloul can you have a look at the conflicts? Thanks!

2023-11-17 07:33 UTC, zsinnema commented
@Salam-Dalloul still a conflict remains. Can you have a look? thanks!

2023-11-17 09:49 UTC, merged