SCKAN-254: opening FW connection chip and link in a new tab
MetaCell/sckan-composer pull request #209
Opened 2024-01-18 15:23 UTC by ddelpiano

2024-01-18 17:05 UTC, afonsobspinto approved these changes

2024-01-18 17:47 UTC, afonsobspinto requested changes

2024-01-18 17:47 UTC, afonsobspinto commented on frontend/src/components/Forms/StatementForm.tsx
> +            window.open(window.location.origin + "/statement/" + entity?.id, '_blank')
Shouldn't this be onClick?

2024-01-18 17:51 UTC, afonsobspinto approved these changes

2024-01-19 09:48 UTC, zsinnema commented
@ddelpiano can we merge?

2024-01-19 10:13 UTC, merged