#255 Frontend UI changes for the export state
MetaCell/sckan-composer pull request #217
Opened 2024-02-07 13:02 UTC by Salam-Dalloul

2024-02-07 19:37 UTC, afonsobspinto requested changes

2024-02-07 19:37 UTC, afonsobspinto commented on frontend/src/components/Widgets/CustomEntitiesDropdown.tsx
> +                !isAllSelectedValuesFromTheAboveLayer ? 0 : selectedOptions?.length
nitpick (non-blocking): isAllSelectedValuesFromTheAboveLayer should be named areAllSelectedValuesFromTheAboveLayer

2024-02-07 19:37 UTC, afonsobspinto commented on frontend/src/components/Widgets/CustomEntitiesDropdown.tsx
> +       isFormDisabled = () => false,
question (if-minor) Why do we have isFormDisabled and disabled props? Don't they represent the same?

2024-02-08 10:49 UTC, ddelpiano commented on frontend/src/Pages/StatementDetails.tsx
> +  const disabled = statement?.state === statementStates.Excluded;
the only states agreed for the read only are exported and invalid. Thanks both

2024-02-08 13:17 UTC, afonsobspinto approved these changes

2024-02-08 13:23 UTC, zsinnema approved these changes

2024-02-08 13:23 UTC, merged