Feature/esckan-35 - Composer REST new generic endpoint
MetaCell/sckan-composer pull request #253
Opened 2024-04-01 11:45 UTC by D-GopalKrishna

Jira Card - https://metacell.atlassian.net/browse/ESCKAN-35

A new generic endpoint for Connectivity statement.
- Add new endpoint `connectivity-statement-generic` with new serializer - GenericConnectivityStatementSerializer and filterset - GenericConnectivityStatementFilter.
- Only GET allow.
- filter by 4 query parameters - origin, via, destination, population uris
-  Only exported Connectivity statements are shown. As mentioned in [lucidcharts](https://lucid.app/lucidchart/7197f056-4f35-4453-8f27-369a045ad40b/edit?invitationId=inv_d553a755-dc0e-44bc-ac75-f15e4be38e13&page=.eqhIXv27vP.#)

<br>

Default behaviors of the filters.
- When multiple population uris are selected - OR is applied.
- When one population and one via/origin/destination is selected - AND is applied

Source on Custom Filter with [django_filters](https://django-filter.readthedocs.io/en/stable/ref/filters.html#multiplechoicefilter)

Short video demo

https://github.com/MetaCell/sckan-composer/assets/59233227/24cedd2b-7fc7-4530-b103-cf46acceb40c

2024-04-01 11:49 UTC, D-GopalKrishna commented
@ddelpiano can you please confirm the format of the Response here - 
[response_1711968948434.json](https://github.com/MetaCell/sckan-composer/files/14823048/response_1711968948434.json)

2024-04-02 07:32 UTC, zsinnema requested changes

2024-04-02 07:32 UTC, zsinnema commented on backend/composer/api/urls.py
> +router.register(
question: @D-GopalKrishna what is the difference between Generic and "normal" connectivity statements?

2024-04-02 08:31 UTC, D-GopalKrishna commented on backend/composer/models.py
> +    def ontology_uri(self):
Yes done, and merged here already! and merged to this branch


https://github.com/MetaCell/sckan-composer/pull/252#issuecomment-2031215692

2024-04-03 23:44 UTC, D-GopalKrishna commented
Will be creating a new PR for #ESCKAN-35 - generic composer API.

2024-04-03 23:44 UTC, closed without merging