Feature/esckan-65 - get entities (origin, destination, vias) in the joumey as part of serializer export
MetaCell/sckan-composer pull request #294
Opened 2024-09-18 08:10 UTC by D-GopalKrishna

2024-09-18 17:12 UTC, afonsobspinto requested changes
issue: Would it be possible to update [the journey tests](https://github.com/MetaCell/sckan-composer/blob/develop/backend/tests/test_journey.py) to match with the new format?

2024-09-18 17:15 UTC, afonsobspinto requested changes
question: Would it make sense to run the [genapi.sh](https://github.com/MetaCell/sckan-composer/blob/develop/frontend/genapi.sh) to update the open api specification?

2024-09-18 19:01 UTC, afonsobspinto requested changes
suggestion: It would be good if we also had the ids of the entities in the new entities journey property

2024-09-26 22:44 UTC, ddelpiano approved these changes
lgtm

2024-09-26 22:48 UTC, merged