Feature/sckan 333
MetaCell/sckan-composer pull request #360
Opened 2024-11-17 10:05 UTC by D-GopalKrishna

Jira link - [SCKAN-333](https://metacell.atlassian.net/browse/SCKAN-333)

About task:

1. Backend Logic: -- By default show - show human-created notes & those associated with Invalid and Exported states.
2. Add boolean filter - include_system_notes
3. update openapi spec
4. add checkbox in Frontend, and related logic + update noteService

2024-11-19 12:19 UTC, afonsobspinto commented on backend/composer/api/filtersets.py
> +            Q(user=system_user, note__icontains="exported") |
User experience wise is not obvious why I'm seeing system notes in a situation like this:
![image](https://github.com/user-attachments/assets/e1f32027-1d7b-45b8-a4c7-92a14e896eb8)

2024-11-19 13:00 UTC, afonsobspinto commented on backend/composer/api/filtersets.py
> +        # BELOW LOGIC: if include_system_notes is False, show - system notes associated with "invalid" or "exported" + non_system_notes
nitpik: "Below Logic" is Implied, there's no need to include that expression in the comment

2024-11-20 09:32 UTC, D-GopalKrishna commented on frontend/src/apiclient/backend/api.ts
> +import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
missed it, it was an older one I believe, fixed it now. thanks!!

2024-11-22 14:30 UTC, D-GopalKrishna commented on backend/composer/api/filtersets.py
> +            ~Q(type__in=[NoteType.TRANSITION])
Do not show any transition related notes by default

2024-11-26 09:42 UTC, ddelpiano approved these changes

2024-11-26 10:10 UTC, ddelpiano commented
@D-GopalKrishna an issue here - the export transition should show up as per acceptance criteria

[scrnli_XAuCM5d7WaQ1mi.webm](https://github.com/user-attachments/assets/8674a484-cae7-4cc2-a6b9-752b12440d88)

2024-11-26 10:30 UTC, ddelpiano requested changes
exported missing the filter

2024-11-26 10:34 UTC, D-GopalKrishna commented
thanks @ddelpiano ! Updated it - by removing the logic to - not include the transition notes. 

https://github.com/user-attachments/assets/7f42184e-cb83-473d-82c4-61a1b00d2b10

2024-11-26 11:21 UTC, ddelpiano approved these changes

2024-11-26 11:22 UTC, merged

2024-11-26 11:43 UTC, afonsobspinto approved these changes