Feature/sckan 340 - Adjust default Sentence List view properties
MetaCell/sckan-composer pull request #362
Opened 2024-11-19 09:59 UTC by D-GopalKrishna

Jira link - [SCKAN-340](https://metacell.atlassian.net/browse/SCKAN-340)

**Task description:**

Sorting by last edited is straight forward. Sorting by owner is done as following rule (please let me know if this sounds wrong or any other feedback):

- keep the empty owner Sentences last; at all times. Reasoning behind it - if you are trying to sort by owner, then you should see the most relevant information first (which is not the empty owner). So for both ascending and descending sorting - we keep the empty owners at last.
- If no sorting is applied - you see - Sentences sorted by - date (second priority) and owner (first priority) (see owner’s Sentences first)
- If sorting by last edited - asc (see oldest first) or desc (see latest first)
- If sorting by owner:
    - asc - keep the empty owner Sentences last (first priority) → See the owner’s Sentences first (second priority) → Sort by owner’s full name in asc order (third priority)
    - desc - keep the empty owner Sentences last (first priority) → See the owner’s Sentences last (second priority) → Sort by owner’s full name in desc order (third priority)

2024-11-19 13:08 UTC, afonsobspinto requested changes
I believe this point is missing from the acceptance criteria 
>3. Apply filters by default upon login to show only sentences with the following statuses: compose later; compose now; needs further review; open; ready to compose.

2024-11-20 10:29 UTC, D-GopalKrishna commented
> I believe this point is missing from the acceptance criteria
> 
> > 3. Apply filters by default upon login to show only sentences with the following statuses: compose later; compose now; needs further review; open; ready to compose.


thanks alot @afonsobspinto ! here fixed. 
![image](https://github.com/user-attachments/assets/2224b1ee-4abd-4ecd-8072-ebb2529a6c73)

2024-11-20 21:24 UTC, afonsobspinto submitted a review, later dismissed

2024-11-26 10:32 UTC, ddelpiano requested changes

2024-11-26 10:32 UTC, ddelpiano commented on frontend/src/App.tsx
> +      ComposerSentenceListStateEnum.ComposeLater, ComposerSentenceListStateEnum.ComposeNow,
Missing the open state.

From the acceptance criteria:
Apply filters by default upon login to show only sentences with the following statuses: compose later; compose now; needs further review; **open**; ready to compose.

2024-11-26 10:37 UTC, ddelpiano commented
@D-GopalKrishna a bonus request, could we change the last edit for a sentence or a statement if we add/remove a tag from this record or there is a new message? Thanks

2024-11-26 12:52 UTC, D-GopalKrishna commented
> @D-GopalKrishna a bonus request, could we change the last edit for a sentence or a statement if we add/remove a tag from this record or there is a new message? Thanks

done @ddelpiano, thanks!! 
here's a v-demo 

https://github.com/user-attachments/assets/eec5b320-870a-4a05-b016-244c2b83c117

2024-11-26 14:02 UTC, ddelpiano approved these changes

2024-11-26 14:03 UTC, merged