SCKAN-287 Update Automated tests
MetaCell/sckan-composer pull request #366
Opened 2024-11-22 17:19 UTC by SimaoBolota-MetaCell

2024-11-22 18:04 UTC, SimaoBolota-MetaCell commented
@ddelpiano there seem to be issues on the sckan-qa pipeline that used to run the tests. Should I also check that?

2024-12-13 11:07 UTC, ddelpiano requested changes
@SimaoBolota-MetaCell I can see there have been changes to the package.json, could you please separate the testing dependencies in another package.json to keep in the test folder please?

I prefer do not impact the application dependencies for testing updates or upgrades we want to do with the libraries used for QA, and so separate them will keep them indipendent. Thanks.

2025-01-06 17:59 UTC, afonsobspinto commented on frontend/package-lock.json
For the same reasons mentioned here: https://github.com/MetaCell/sckan-composer/pull/366#pullrequestreview-2502041609. I wouldn't expect changes on this file either

2025-01-06 18:06 UTC, afonsobspinto commented on backend/backend/settings.py
> +TESTING = os.environ.get("TESTING", "False").lower() in ("true", "1")
https://metacell.atlassian.net/browse/SCKAN-375?focusedCommentId=16635

2025-01-07 14:04 UTC, SimaoBolota-MetaCell commented on frontend/package-lock.json
Fixed that, thanks for spotting it!

2025-01-08 11:07 UTC, ddelpiano approved these changes

2025-01-08 11:07 UTC, merged